baseURL = 'http://ywzhang.me/'
languageCode = 'en-us'
title = "微风细雨"
theme = 'ananke'

[taxonomies]
  category = "categories"
  tag = "tags"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Zhang Yiwu"
  favicon = ""
  site_logo = ""
  featured_image: "/images/nightrain.jpg"
  description = "Yiwu's Personal Blog."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/zhangyiwu"